name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Get tag name
      id: tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build XCFramework
      run: |
        chmod +x build-xcframework.sh
        ./build-xcframework.sh CacheKit

    - name: Calculate checksum
      id: checksum
      run: |
        CHECKSUM=$(shasum -a 256 build/CacheKit.xcframework.zip | cut -d' ' -f1)
        echo "CHECKSUM=$CHECKSUM" >> $GITHUB_OUTPUT
        echo "Checksum: $CHECKSUM"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload XCFramework to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/CacheKit.xcframework.zip
        asset_name: CacheKit.xcframework.zip
        asset_content_type: application/zip

    - name: Update Package.swift
      run: |
        # Update Package.swift with new URL and checksum
        sed -i '' "s|url: \"https://github.com/BBC6BAE9/cachekit/releases/download/.*/CacheKit.xcframework.zip\"|url: \"https://github.com/BBC6BAE9/cachekit/releases/download/${{ steps.tag.outputs.TAG_NAME }}/CacheKit.xcframework.zip\"|g" Package.swift
        sed -i '' "s|checksum: \".*\"|checksum: \"${{ steps.checksum.outputs.CHECKSUM }}\"|g" Package.swift
        echo "Updated Package.swift for tag ${{ steps.tag.outputs.TAG_NAME }} with checksum ${{ steps.checksum.outputs.CHECKSUM }}"

    - name: Commit updated Package.swift
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Package.swift
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Package.swift for release ${{ steps.tag.outputs.TAG_NAME }}"
          git push origin HEAD:main
        fi
